dataloader:
  batch_size: 128
  num_workers: 10
  path: /fastdata/imagenet256
  persistent_workers: true
  pin_memory: true
  transforms:
    CenterCrop:
      height: 224
      width: 224
    HorizontalFlip: {}
    RGBShift: {}
    RandomCrop:
      height: 224
      width: 224
logger:
  name: test
  project: alexnet
model: Alexnet
optimizer: SGD
optimizer_params:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005
scheduler: null
train:
  accelerator: gpu
  devices: 2
  enable_checkpointing: true
  limit_train_batches: 100
  limit_val_batches: 100
  max_epochs: 10
  overfit_batches: false
