model: Alexnet
optimizer: SGD
optimizer_params:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005
# scheduler: ReduceLROnPlateau
# scheduler_params:
#   patience: 1
#   factor: 0.1
dataloader:
  path: /fastdata/imagenet256
  batch_size: 128
  transforms:
    RandomCrop:
      width: 224
      height: 224
    HorizontalFlip: {}
    RGBShift: {}
train:
  epochs: 90
